CC = gcc
INCLUDES =
CFLAGS = -g -Wall
LDFLAGS = 
LDLIBS =

.PHONY: default
default: mdb-lookup-server-nc-2 mdb-lookup-server-nc-1

mdb-lookup-server-nc-2:

mdb-lookup-server-nc-1:

.PHONY: clean
clean:
	rm -f *.o mdb-lookup-server-nc-2 mdb-lookup-server-nc-1

.PHONY: all
all: clean default

