CC  = gcc
CXX = g++

INCLUDES = 
CFLAGS   = -g -Wall $(INCLUDES)
CXXFLAGS = -g -Wall $(INCLUDES)

LDFLAGS = 
LDLIBS = 

http-client:

.PHONY: clean
clean:
	rm -f *.o *~ a.out core http-client

.PHONY: all
all: clean http-client

